prjBookMvcCore/Models/Artical.cs
using System;
using System.Collections.Generic;

namespace prjBookMvcCore.Models
{
    public partial class Artical
    {
        public Artical()
        {
            ArticalToBookDetails = new HashSet<ArticalToBookDetail>();
        }

        public int ArticalId { get; set; }
        public DateTime ArticalDate { get; set; }
        public string ArticalTitle { get; set; } = null!;
        public string ArticalDescription { get; set; } = null!;
        public byte[]? ArticalPicture { get; set; }

        public virtual ICollection<ArticalToBookDetail> ArticalToBookDetails { get; set; }
    }
}

prjBookMvcCore/Controllers/ArticalController.cs
using Microsoft.AspNetCore.Mvc;
using prjBookMvcCore.Models;

namespace prjBookMvcCore.Controllers
{
    public class ArticalController : Controller
    {
        public IActionResult List全部文章() 
        {
            BookShopContext db=new();
            var datas = db.Articals.OrderByDescending(a=>a.ArticalId).Select(a=>a);
            return View(datas); 
        }

        public IActionResult Detail文章(int? id)
        {
            if (id == null) { return RedirectToAction("List全部文章"); }
            ViewBag.ArticalId = id;
            return View();
            //BookShopContext db = new BookShopContext();
            //var datas=db.ArticalToBookDetails.Where(d=>d.ArticalId==id).Select(d=>d);
            //return View(datas);
        }
      

        //public IActionResult Index() { return View(); }
    }
}

prjBookMvcCore/Views/Artical/Detail文章.cshtml
@model prjBookMvcCore.Models.ArticalToBookDetail

@{ ViewData["Title"] = "Detail文章";}

<!DOCTYPE html>
<html>
    <head>
    <style>
        .imgT{ width:80%;max-width:100%;}

        .imgB { width: 100%;}

        .fig1 {width: 10%;
            /* float: left;*/
            font-size: 80%;margin-right: 10px;
            padding: 10px;
            border: 2px dotted #F2E6E6;
            border-radius: 0 25px 0 25px;
        }

        .date {color: gray;font-style: oblique;font-size: 60%; text-align: right;}

        p { font-family: 標楷體;  margin: 20px 0;  text-align: justify; text-indent: 2em;}

        </style>
    </head>
    <body>
    @{
        int ArticalId = ViewBag.ArticalId;
        BookShopContext db = new BookShopContext();
        var Artical = db.Articals.Where(a => a.ArticalId == ArticalId).Select(a => a).ToList();
        foreach( var g in Artical)
        {string path =g.ArticalTitle+".jpg";
                    <h1>@g.ArticalTitle</h1>
                    <p class="date">更新日期：@g.ArticalDate</p>
                    <div style="text-align:center"><img src="~/Image/ArticalPicture/@path" class="imgT" title="@g.ArticalTitle" /></div>    
                    <p>@g.ArticalDescription</p>
        }
        var detail = db.ArticalToBookDetails.Where(d => d.ArticalId == ArticalId).Select(d => new{ d.Book.BookTitle, d.Book.Isbn, d.Book.UnitPrice, d.Book.Introduction, d.Book.CoverPath, d.Book.BookId,d.Book.PublicationDate,}).ToList();
        foreach(var g in detail)
        {
            var q作者 = db.AuthorDetails.Where(a => a.BookId == g.BookId).Select(a => new { a.Author.AuthorName });
            string s = "";
            foreach (var item in q作者) { s += item.AuthorName + "    "; }
            int price原價 = (int)g.UnitPrice;
            string title中 = g.BookTitle.Split("$")[0];

                    <div>
                        <table>
                        <tr>
                            <td>
                                <figure class="fig1">
                                <img class="imgB" src="../../@g.CoverPath" title="@title中" />
                                <figcaption>@title中</figcaption>
                                </figure>
                            </td>
                            <td>
                                <p>作者：@s</p>
                                <p>出版日期：@g.PublicationDate.ToShortDateString()</p>
                                <p>ISBN：@g.Isbn</p>
                            <p>原價：<del style="color:red;font-style:oblique">@price原價</del> 元</p>
                            @{
                                var bookDiscountId = db.BookDiscountDetails.Where(a => a.BookId == g.BookId).Select(a => a.BookDiscountId).FirstOrDefault();
                                var q是否優惠 = bookDiscountId != null ? bookDiscountId.ToString() : "";
                                if (!string.IsNullOrEmpty(q是否優惠))
                                {
                                    var q優惠折數 = db.BookDiscounts.Where(a => a.BookDiscountId == int.Parse(q是否優惠)).Select(a => new { a.BookDiscountName, a.BookDiscountAmount }).FirstOrDefault();
                                    var price優惠價 = $"{q優惠折數.BookDiscountAmount* price原價:0}";
                                    <p>優惠價：@q優惠折數.BookDiscountName @price優惠價 元</p>
                                }
                                    }
                            </td>
                        </tr>
                        <tr><td colspan="2"><p> 簡介：@g.Introduction </p></td> </tr>
                        </table>
                    </div>
        }
    }
    </body>
</html>

prjBookMvcCore/Views/Artical/List全部文章.cshtml
@model IEnumerable<prjBookMvcCore.Models.Artical>

@{
    ViewData["Title"] = "List全部文章";
}
<script>
    $(document).ready
        (

        );
</script>


<h1>全部文章</h1>


<table class="table table-hover align-middle">
    <thead>
        <tr>
            <th>
              序號
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArticalTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArticalDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 0;
            foreach (var item in Model) {
                string path = item.ArticalTitle + ".jpg";
                count++;
                <tr href="~/Artical/Detail文章/@item.ArticalId">
                <td>@count</td>
                    <td>
                        <a href="~/Artical/Detail文章/@item.ArticalId"> <img src="~/Image/ArticalPicture/@path" height="50" width="150" title="@item.ArticalTitle" /> </a><br>
                    @Html.ActionLink(item.ArticalTitle, "Detail文章" , "Artical" ,new{id=item.ArticalId},new{}) 
                </td>
                <td>@Html.DisplayFor(modelItem => item.ArticalDate)  </td>
                </tr>
            }
        }
    </tbody>
</table>