prjBookMvcCore/Controllers/PromotionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;
using prjBookMvcCore.Models;
using System.Net;

namespace prjBookMvcCore.Controllers
{
    public class PromotionsController : Controller
    {
        BookShopContext db = new();
        public UserInforService _userInforService { get; set; }
        public PromotionsController(UserInforService userInforService) { _userInforService = userInforService; }

        public IActionResult Promotions註冊會員禮() { return View(); }
        public IActionResult Promotions會員() { return View(); }
        public IActionResult Promotions促銷活動() { return View(); }
        public IActionResult Promotions促銷(int id, int page = 1)
        {
            if (id != 0)
            {
                ViewBag.Discount = db.BookDiscounts.Where(d => d.BookDiscountId == id).Select(d => d.BookDiscountName).FirstOrDefault();
                int itemsPerPage = 28;//每頁只顯示28個                   
                var bookDiscountDetail = db.BookDiscountDetails.Where(d => d.BookDiscountId == id & d.BookDiscountStartDate < DateTime.Now & d.BookDiscountEndDate > DateTime.Now).Select(d => new { d.BookDiscount.BookDiscountName, d.BookDiscount.BookDiscountAmount, d.Book.BookTitle, d.Book.UnitPrice, d.Book.CoverPath, d.Book.BookId, d.BookDiscountEndDate });

                //頁面顯示控制
                int totalItems = bookDiscountDetail.Count();
                int totalPages = (int)Math.Ceiling((double)totalItems / itemsPerPage);
                int offset = (page - 1) * itemsPerPage;
                var books = bookDiscountDetail.Skip(offset).Take(itemsPerPage);

                List<MenuItem> menuItems = new List<MenuItem>();
                foreach (var item in books)
                {
                    Book b = new Book
                    {
                        BookTitle = item.BookTitle,
                        BookId = item.BookId,
                        UnitPrice = item.UnitPrice,
                        CoverPath = item.CoverPath,
                    };
                    BookDiscount bd = new BookDiscount { BookDiscountAmount = item.BookDiscountAmount, BookDiscountName = item.BookDiscountName, };
                    BookDiscountDetail bdd = new BookDiscountDetail { BookDiscountEndDate = item.BookDiscountEndDate, };
                    MenuItem tmp = new MenuItem();
                    tmp.book = b;
                    tmp.bookDiscount = bd;
                    tmp.bookDiscountDetail = bdd;
                    menuItems.Add(tmp);
                }

                MenuInformation menuInformation = new MenuInformation
                {
                    menuItems = menuItems,
                    CurrentPage = page,
                    TotalPages = totalPages,
                    bookDiscountId = id,
                };
                return View(menuInformation);
            }
            else { return RedirectToAction("Promotions促銷活動"); }
        }
        public IActionResult Promotions活動總覽圖()
        {
            var datas = db.Articals.OrderByDescending(a => a.ArticalId).Where(a => a.ArticalId != 8 & a.ArticalId != 10 & a.ArticalId != 17).Select(a => a);
            return View(datas);
        }
        public IActionResult Promotions活動總覽表()
        {
            var datas = db.Articals.OrderByDescending(a => a.ArticalId).Where(a => a.ArticalId != 8 & a.ArticalId != 10 & a.ArticalId != 17).Select(a => a);
            return View(datas);
        }
        public IActionResult Promotions活動圖()
        {
            var datas = db.Articals.OrderByDescending(a => a.ArticalId).Where(a => a.ArticalId == 8 || a.ArticalId == 10 || a.ArticalId == 17).Select(a => a);
            return View(datas);
        }
        public IActionResult Promotions活動表()
        {
            var datas = db.Articals.OrderByDescending(a => a.ArticalId).Where(a => a.ArticalId == 8 || a.ArticalId == 10 || a.ArticalId == 17).Select(a => a);
            return View(datas);
        }
        public IActionResult Promotions活動文章Detail(int? id)
        {
            if (id == null) { return RedirectToAction("Promotions活動已結束"); }
            ViewBag.ArticalId = id;
            return View();
        }
        public IActionResult Promotions活動已結束() { return View(); }
        public IActionResult Index() { return View(); } //預設為 建置中
        public IActionResult Promotions領取當周優惠() { return View(); }
        public string Promotions領取特定日優惠(int discountID, DateTime date, int time)
        {
            string isSuccess;
            var q = db.OrderDiscountDetails.Where(d => d.MemberId == _userInforService.UserId & d.OrderDiscountId == discountID & d.OrderDiscountStartDate == date).Select(d => d);
            if (q.Count() != 0)
            {
                isSuccess = "false";
                return isSuccess;
            }
            else
            {
                OrderDiscountDetail newmemberdiscount = new OrderDiscountDetail()
                {
                    OrderDiscountId = discountID,
                    MemberId = _userInforService.UserId,
                    OrderDiscountStartDate = date,
                    OrderDiscountEndDate = date.AddDays(time),
                };
                db.OrderDiscountDetails.Add(newmemberdiscount);
                db.SaveChanges();
                isSuccess = "true";
                return isSuccess;
            }
        }

        public string Promotions限時登入領取優惠()
        {
            string isSuccess;
            var q = db.OrderDiscountDetails.Where(d => d.MemberId == _userInforService.UserId & d.OrderDiscountId == 4).Select(d => d);
            if (q.Count() != 0)
            {
                isSuccess = "false";
                return isSuccess;
            }
            else
            {
                OrderDiscountDetail newmemberdiscount = new OrderDiscountDetail()
                {
                    OrderDiscountId = 4,
                    MemberId = _userInforService.UserId,
                    OrderDiscountStartDate = DateTime.Now,
                    OrderDiscountEndDate = DateTime.Now.AddDays(3),
                };
                db.OrderDiscountDetails.Add(newmemberdiscount);
                db.SaveChanges();
                isSuccess = "true";
                return isSuccess;
            }
        }
        //TODO：會員等級
        //public IActionResult Promotions領取月優惠(int? month)
        //{
        //    if (month == null || month < DateTime.Now.Month) { return RedirectToAction("Promotions活動已結束"); }
        //    else if (month > DateTime.Now.AddMonths(2).Month) { return RedirectToAction("Index"); }
        //    else { ViewBag.month = month; return View(); }
        //}

        public IActionResult SearchTest(string? txtKeyword)
        {
            ViewBag.KeyWord = txtKeyword;
            BookShopContext db = new BookShopContext();
            if (string.IsNullOrEmpty(txtKeyword))
            {
                var s書 = db.Books.Select(b => b).ToList();
                return View(s書);
            }
            else
            {
                var s書 = db.Books.Where(p => p.BookTitle.Contains(txtKeyword) || p.Isbn.Contains(txtKeyword)).ToList();
                var s作者 = db.Authors.Where(a => a.AuthorName.Contains(txtKeyword)).ToList();
                var s譯者 = db.Translators.Where(t => t.TranslatorName.Contains(txtKeyword)).ToList();
                var s繪者 = db.Painters.Where(p => p.PainterName.Contains(txtKeyword)).ToList();
                var s出版社 = db.Publishers.Where(p => p.PublisherName.Contains(txtKeyword)).ToList();
                var s分類 = db.Categories.Where(c => c.CategoryName.Contains(txtKeyword)).ToList();
                CSearch sTest = new CSearch
                {
                    c書 = s書,
                    c作者 = s作者,
                    c譯者 = s譯者,
                    c繪者 = s繪者,
                    c出版社 = s出版社,
                    c分類 = s分類
                };
                return View(sTest);
            }
        }
    }
}
namespace prjBookMvcCore.Models
{
    public class CSearch
    {
        public List<Book>? c書 { get; set; }
        public List<Author>? c作者 { get; set; }
        public List<Translator>? c譯者 { get; set; }
        public List<Painter>? c繪者 { get; set; }
        public List<Publisher>? c出版社 { get; set; }
        public List<Category>? c分類 { get; set; }
    }
}

prjBookMvcCore/Views/Promotions/Index.cshtml
@{
    ViewData["Title"] = "建置中";
}
<div class="col" style="text-align:center">
    <img src="~/Image/網頁建置中.gif" alt="網頁建置中" width="100%" />
</div>

prjBookMvcCore/Views/Promotions/Promotions會員.cshtml
@{
    ViewData["Title"] = "讀本會員等級";
}
<html>
<head>
    <style>
        h1 {
            color: brown;
            text-align: center;
            font-weight: 900;
        }

        td {
            padding: 15px;
        }

        table img {
            width: 100px;
            margin: 10px;
        }

        table span {
            font-style: italic;
            font-weight: bold;
            color: brown;
        }
    </style>
</head>
<body>
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="text-decoration-none" href="~/Home/Home" style="color:black">首頁</a></li>
            <li class="breadcrumb-item"><a class="text-decoration-none" href="~/Home/QA" style="color:black">Q&A</a></li>
            <li class="breadcrumb-item active" aria-current="page" style="color:gray">會員等級優惠及升等方式</li>
        </ol>
    </nav>
    <h1>會員等級優惠及升等方式</h1>
    <div class="row mt-3" style="display:flex;align-content:center;justify-content:center;">
        <table style="text-align:center;font-size:1.5em">
            <tr style="background-color:	#FBFBFF;font-weight:bold;border-bottom:2px solid brown ;"><td style="border:hidden;"></td><td rowspan="6" style="background-color:	#FFFFF4;">等<br />級<br />優<br />惠</td><td><img src="~/Image/Promotions/生日禮.png" /><br />生日禮</td><td><img src="~/Image/Promotions/滿千折扣.png" /><br />滿千折扣</td><td><img src="~/Image/Promotions/滿千回饋.png" /><br />滿千回饋</td><td><img src="~/Image/Promotions/每月優惠卷.png" /><br />每月優惠劵</td><td rowspan="6" style="background-color:	#FFFFF4">升<br />等<br />方<br />式</td><td><img src="~/Image/Promotions/累積消費.png" /><br />累積消費</td><td><img src="~/Image/Promotions/累積週期.png" /><br />累積週期</td></tr>
            <tr><td style="background-color:	#FBFBFF;font-weight:bold;"><img src="~/Image/新皮.png" /><br />新皮</td><td>生日當月送<br /><span>滿699折66</span><br />Coupon 乙張</td><td> - </td><td> - </td><td> -</td><td></td><td rowspan="5" width="150px">前年度的<br />8/1至<br />當年度的<br />7/31止</td></tr>
            <tr><td style="background-color:	#FBFBFF;font-weight:bold;"><img src="~/Image/綠皮.png" /><br />綠皮</td><td>生日當月送<br /><span>滿699折66</span><br />Coupon 乙張</td><td>單筆滿千享<br /><span>95折</span><br />優惠</td><td> - </td><td> - </td><td>累積消費達<br /><span>1</span>元</td></tr>
            <tr><td style="background-color:	#FBFBFF;font-weight:bold;"><img src="~/Image/白皮.png" /><br />白皮</td><td>生日當月送<br /><span>滿699折66</span><br />Coupon 乙張</td><td>單筆滿千享<br /><span>95折</span><br />優惠</td><td>單筆滿千送<br /><span>1%</span><br />回饋金</td><td> - </td><td>累積消費達<br /><span>2500</span>元</td></tr>
            <tr><td style="background-color:	#FBFBFF;font-weight:bold;"><img src="~/Image/金皮.png" /><br />金皮</td><td>生日當月送<br /><span>滿699折66</span><br />Coupon 乙張</td><td>單筆滿千享<br /><span>9折</span><br />優惠</td><td>單筆滿千送<br /><span s>1%</span><br />回饋金</td><td>每月送<br /><span>滿399折20</span><br />Coupon 乙張</td><td>累積消費達<br /><span>5000</span>元</td></tr>
            <tr><td style="background-color:	#FBFBFF;font-weight:bold;"><img src="~/Image/鑽皮.png" /><br />鑽皮</td><td>生日當月送<br /><span>滿699折66</span><br />Coupon 乙張</td><td>單筆滿千享<br /><span>85折</span><br />優惠</td><td>單筆滿千送<br /><span>5%</span><br />回饋金</td><td>每月送<br /><span>滿399折40</span><br />Coupon 乙張</td><td>累積消費達<br /><span>7500</span>元</td></tr>
        </table>
        <div class="row p-2" style="background-color:black;color:aliceblue;"><div class="col" style="font-size:2em;font-weight:bold;text-align:right;">注意 |</div><div class="col"><div class="row">1.訂單完成才列入升等計算</div><div class="row"> 2.優惠卷限當月使用，早領早享受</div></div>​</div>
    </div>
</body>
</html>

prjBookMvcCore/Views/Promotions/Promotions活動已結束.cshtml
@{
    ViewData["Title"] = "活動已結束";
}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
</head>
<body>
    <div class="container_24 type04_header_simplify  clearfix" id="header_id" data-attr="simple">
        <div class="grid_24 clearfix">
            <div class="mod header_box clearfix" style="background-image:url(https://www.books.com.tw/G/header/2008/new_header/images/books_logo_a.gif)">
            </div>
        </div>
    </div>
    <link rel="stylesheet" href="//www.books.com.tw/csss/404page.css">
    <div class="container_24 main_wrap clearfix">
        <h1 class="msg_title">錯誤頁面訊息提示</h1>
        <div class="msg_count">
            <div class="msg">
                <h2 class="msg_info">活動已結束</h2>
                <p><a href="~/Home/Home">回讀本首頁</a></p>
            </div><span class="msg_pic"></span>
        </div>
        <div class="msg_end"></div>
    </div>
</body>
</html>

prjBookMvcCore/Views/Promotions/Promotions活動總覽表.cshtml
@model IEnumerable<prjBookMvcCore.Models.Artical>
@{
    ViewData["Title"] = "推薦專文";
}
<html>
<body>
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="text-decoration-none" href="~/Home/Home" style="color:black">首頁</a></li>
            <li class="breadcrumb-item active" aria-current="page" style="color:gray">推薦專文</li>
        </ol>
    </nav>
    <h1>推薦專文</h1>
    <div style="text-align:right;">
        <a role="button" class="btn  btn-outline-secondary mx-1" href="~/Promotions/Promotions活動總覽圖">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-grid-3x3-gap-fill" viewBox="0 0 16 16">
                <path d="M1 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2zM1 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V7zM1 12a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2z" />
            </svg>專文圖
        </a>
        <a role="button" class="btn  btn-secondary mx-1" href="~/Promotions/Promotions活動總覽表">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-stars" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5z" />
                <path d="M2.242 2.194a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.277.277 0 0 0-.094.3l.173.569c.078.256-.213.462-.423.3l-.417-.324a.267.267 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.277.277 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.271.271 0 0 0 .259-.194l.162-.53zm0 4a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.277.277 0 0 0-.094.3l.173.569c.078.255-.213.462-.423.3l-.417-.324a.267.267 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.277.277 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.271.271 0 0 0 .259-.194l.162-.53zm0 4a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.277.277 0 0 0-.094.3l.173.569c.078.255-.213.462-.423.3l-.417-.324a.267.267 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.277.277 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.271.271 0 0 0 .259-.194l.162-.53z" />
            </svg>專文表
        </a>
    </div>
    <br />
    <table class="table table-hover align-middle" style="text-align:center">
        <thead>
            <tr>
                <th>
                    序號
                </th>
                <th>
                    標題
                </th>
                <th>
                    更新日期
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                @{
                    int count = 0;
                    foreach (var item in Model)
                    {
                        string path = item.ArticalTitle + ".jpg";
                        count++;
                        string date = item.ArticalDate.ToString("yyyy/MM/dd");
                    <tr>
                        <td>@count</td>
                        <td>
                                @Html.ActionLink(item.ArticalTitle, "Promotions活動文章Detail" , "Promotions" ,new{id=item.ArticalId},new{@class="link-secondary"})
                        </td>
                        <td>@date </td>
                    </tr>
                    }
                }
        </tbody>
    </table>
</body>
</html>

prjBookMvcCore/Views/Promotions/Promotions活動表.cshtml
@model IEnumerable<prjBookMvcCore.Models.Artical>
@{
    ViewData["Title"] = "活動總覽";
}
<html>
<body>
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="text-decoration-none" href="~/Home/Home" style="color:black">首頁</a></li>
            <li class="breadcrumb-item active" aria-current="page" style="color:gray">活動總覽</li>
        </ol>
    </nav>
    <h1>活動總覽</h1>
    <div style="text-align:right;">
        <a role="button" class="btn  btn-outline-secondary mx-1" href="~/Promotions/Promotions活動圖">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-grid-3x3-gap-fill" viewBox="0 0 16 16">
                <path d="M1 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2zM1 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V7zM1 12a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2z" />
            </svg>活動圖
        </a>
        <a role="button" class="btn  btn-secondary mx-1" href="~/Promotions/Promotions活動表">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-stars" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5z" />
                <path d="M2.242 2.194a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.277.277 0 0 0-.094.3l.173.569c.078.256-.213.462-.423.3l-.417-.324a.267.267 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.277.277 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.271.271 0 0 0 .259-.194l.162-.53zm0 4a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.277.277 0 0 0-.094.3l.173.569c.078.255-.213.462-.423.3l-.417-.324a.267.267 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.277.277 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.271.271 0 0 0 .259-.194l.162-.53zm0 4a.27.27 0 0 1 .516 0l.162.53c.035.115.14.194.258.194h.551c.259 0 .37.333.164.493l-.468.363a.277.277 0 0 0-.094.3l.173.569c.078.255-.213.462-.423.3l-.417-.324a.267.267 0 0 0-.328 0l-.417.323c-.21.163-.5-.043-.423-.299l.173-.57a.277.277 0 0 0-.094-.299l-.468-.363c-.206-.16-.095-.493.164-.493h.55a.271.271 0 0 0 .259-.194l.162-.53z" />
            </svg>活動表
        </a>
    </div>
    <br />
    <table class="table table-hover align-middle" style="text-align:center">
        <thead>
            <tr>
                <th>
                    序號
                </th>
                <th>
                    標題
                </th>
                <th>
                    更新日期
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>
                    @Html.ActionLink("註冊會員禮", "Promotions註冊會員禮" , "Promotions" ,new{},new{@class="link-secondary"})
                </td>
                <td> 持續優惠中 </td>
            </tr>
            <tr>
                <td>2</td>
                <td>
                    @Html.ActionLink("促銷活動", "Promotions促銷活動" , "Promotions" ,new{},new{@class="link-secondary"})
                </td>
                <td> 持續更新中 </td>
            </tr>
            @{
                int count = 2;
                foreach (var item in Model)
                {
                    string path = item.ArticalTitle + ".jpg";
                    count++;
                    string date = item.ArticalDate.ToString("yyyy/MM/dd");
                    <tr>
                        <td>@count</td>
                        <td>
                            @Html.ActionLink(item.ArticalTitle, "Promotions活動已結束" , "Promotions" ,new{id=item.ArticalId},new{@class="link-secondary"})
                        </td>
                        <td>已結束 </td>
                    </tr>
                }
                <tr>
                    <td>@count</td>
                    <td>
                        @Html.ActionLink("配著小說許下未來心願", "Promotions活動已結束" , "Promotions" ,new{},new{@class="link-secondary"})
                    </td>
                    <td>已結束 </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

prjBookMvcCore/Views/Promotions/Promotions領取月優惠.cshtml
@inject UserInforService _userInforService
@{
    ViewData["Title"] = "Promotions領取月優惠";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    
</head>
<body>
    <h1>領取 @ViewBag.month 月滿額折扣</h1>
   @*
    12	2	520折扣	滿520扣99
    13	2	666折扣	滿666扣66
    14	2	滿額折扣	滿2499扣299
    15	2	滿額折扣	滿1699扣199
    16	2	滿額折扣	滿1299扣139
    17	2	滿額折扣	滿888扣88

       每周三：
       每周六日：
       月中：
   *@
    @{
        var day = DateTime.Now.DayOfYear;
    }
</body>
</html>
<script>
    let isLogin = false;
    window.onload = () => {
        if (@_userInforService.UserId !== 0) {
            isLogin = true;
        };
        console.log(isLogin);
    };

    function loginCheck() {
        if (isLogin === false) {
            alert('尚未登入');
            if (confirm('前往登入')) {
                window.location.href = "../../Member/Login";
            } else {
            }
            return false;
        }
        return true;
    };

    function takeCoupon(memberID, discountID, date) {
        if (loginCheck()) {
            let url = '@Url.Action("Promotions領取特定日優惠","Promotions")?memberID=' + memberID + '&discountID=' + discountID + '&date=' + date;
            $.ajax({
                url: url,
                type: 'POST',
                success: function (result) {
                    let isSuccess = result;
                    if (isSuccess === "false") { alert('已領取'); }
                    else { alert('領取成功'); }
                },
            });
        }
    };
</script>